In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Reference the file where the CSV is located
crime_csv_path = "Resources/crime_incident_data2017.csv"

# Import the data into a Pandas DataFrame
crime_df = pd.read_csv(crime_csv_path)
crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [3]:
# look for missing values
crime_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [4]:
# drop null rows
no_null_crime_df = crime_df.dropna(how='any')

In [5]:
# verify counts
no_null_crime_df.count()

Address              36146
Case Number          36146
Crime Against        36146
Neighborhood         36146
Number of Records    36146
Occur Date           36146
Occur Month Year     36146
Occur Time           36146
Offense Category     36146
Offense Count        36146
Offense Type         36146
Open Data Lat        36146
Open Data Lon        36146
Open Data X          36146
Open Data Y          36146
Report Date          36146
Report Month Year    36146
dtype: int64

In [6]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       2824
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
Theft From Building                             895
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    145
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     73
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Welfare Fraud                                     1
Commercial Sex Acts                               1
Name: Offense Type, dtype: int64

In [7]:
# Combining similar offenses together
no_null_crime_df = no_null_crime_df.replace(
    {"Commercial Sex Acts": "Prostitution", "Assisting or Promoting Prostitution": "Prostitution"})
no_null_crime_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
5,5400 BLOCK OF NE MALLORY AVE,17-900129,Property,King,1,11/28/10,11/1/10,1612,Fraud Offenses,1,Identity Theft,45.5625,-122.664,7647987.0,698581.0,1/3/17,1/1/17
6,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
7,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,Identity Theft,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
8,12000 BLOCK OF SE PINE ST,17-900253,Property,Hazelwood,1,1/6/14,1/1/14,805,Fraud Offenses,1,Credit Card/ATM Fraud,45.5204,-122.539,7679522.0,682404.0,1/6/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41026,10200 BLOCK OF NE SANDY BLVD,17-286419,Society,Parkrose,1,8/31/17,8/1/17,2005,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5591,-122.557,7675224.0,696649.0,8/31/17,8/1/17
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [8]:
# Check to see if you comnbined similar offenses correctly in "Offense Type".
no_null_crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       2824
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
Theft From Building                             895
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    153
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     73
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [10]:
# Get the number of crimes against property, society, and person.
no_null_crime_df["Crime Against"].value_counts()

Property    31622
Person       2978
Society      1546
Name: Crime Against, dtype: int64